-- ============================================
-- SEED DATA: 150,000 Products
-- Run seed.sql first to create departments/categories
-- ============================================

INSERT INTO product (product_barcode, product_name, product_buyprice, product_sellprice, product_category_id, product_department_id)
SELECT
    '899' || LPAD(i::text, 9, '0') AS product_barcode,
    sub.name AS product_name,
    ROUND(((i * 7 + 1234) % 95000 + 500)::numeric, 2) AS product_buyprice,
    ROUND(((i * 7 + 1234) % 95000 + 500 + (i * 3) % 30000 + 5000)::numeric, 2) AS product_sellprice,
    (i % 6) + 1 AS product_category_id,
    (i % 5) + 1 AS product_department_id
FROM generate_series(1, 150000) AS i
CROSS JOIN LATERAL (
    SELECT
        (ARRAY[
            'Indomie Goreng Original', 'Indomie Goreng Soto', 'Indomie Goreng Ayam Bawang',
            'Indomie Goreng Sambal Matah', 'Indomie Goreng Rendang', 'Indomie Goreng Kaldu Ayam',
            'Indomie Kuah Soto', 'Indomie Kuah Ayam Bawang', 'Indomie Kuah Soto Mie',
            'Indomie Kuah Kari Ayam', 'Indomie Kuah White Pepper', 'Indomie Kuah Bakso',
            'Teh Sosro Botol 350ml', 'Teh Sosro Botol 450ml', 'Teh Sosro Kotak 200ml',
            'Le Minerale 600ml', 'Le Minerale 1500ml', 'Le Minerale 330ml',
            'Aqua 350ml', 'Aqua 600ml', 'Aqua 1500ml', 'Aqua 2L',
            'Kapal Api 200g', 'Kapal Api 100g', 'Kapal Api Special 200g',
            'Good Day Cappuccino 10s', 'Good Day Mocha 10s', 'Good Day Vanilla 10s',
            'Good Day Original 15s', 'Good Day Cappuccino 20s',
            'Extra Joss 10s', 'Extra Joss 15s', 'Extra Joss Active 10s',
            'Rinso Anti Noda 800g', 'Rinso Matic 800g', 'Rinso Formula 1kg',
            'Rinso Anti Noda 1.6kg', 'Rinso Matic 1.6kg',
            'Sunlight Jeruk Nipis 755ml', 'Sunlight Lemon 755ml', 'Sunlight Jeruk Nipis 455ml',
            'Lifebuoy Activ Silver 100g', 'Lifebuoy Total 10 100g', 'Lifebuoy Mild Care 100g',
            'Bimoli Spesial 2L', 'Bimoli Spesial 1L', 'Bimoli Cap Lang 2L',
            'Sania Beras Premium 5kg', 'Sania Beras Premium 10kg', 'Sania Beras Pull Mazuna 5kg',
            'Segitiga Biru 1kg', 'Segitiga Biru 500g', 'Segitiga Biru 5kg',
            'Palmia Margarin 200g', 'Palmia Margarin 500g', 'Palmia Serbaguna 200g',
            'Fortune Minyak Goreng 2L', 'Fortune Minyak Goreng 1L', 'Fortune Minyak Goreng 5L',
            'So Good Chicken Nugget 400g', 'So Good Chicken Nugget 200g', 'So Good Tempura 400g',
            'So Good Chicken Katsu 400g', 'So Good Spring Roll 400g',
            'Chitato Sapi Panggang 68g', 'Chitato Ayam Bakar 68g', 'Chitato Balado 68g',
            'Chitato Sapi Lada Hitam 68g', 'Chitato Rumput Laut 68g',
            'Lays Rumput Laut 68g', 'Lays Original 68g', 'Lays Rumput Laut 40g',
            'Qtela Singkong Balado 60g', 'Qtela Singkong Original 60g', 'Qtela Tempe 60g',
            'Taro Net 60g', 'Taro Net 30g', 'Taro Net 100g',
            'Beng-Beng 36g', 'Beng-Beng 72g', 'Beng-Beng Share 168g',
            'Silverqueen Cashew 100g', 'Silverqueen Almond 100g', 'Silverqueen Chunky Bar 100g',
            'Silverqueen Cashew 50g', 'Silverqueen Mix Nuts 100g',
            'Oreo Original 137g', 'Oreo Vanilla 137g', 'Oreo Strawberry 137g',
            'Oreo Mini 45g', 'Oreo Double Stuf 137g',
            'Roma Malkist Crackers 130g', 'Roma Biskuit Kelapa 130g',
            'Roma Malkist Abon 130g', 'Roma Malkist Coconut 130g',
            'Nabati Richeese 100g', 'Nabati Richeese 60g', 'Nabati Richeese 200g',
            'Nabati Keju 60g', 'Nabati Pedas 60g',
            'Nextar Brownies 100g', 'Nextar Srikaya 100g', 'Nextar Coklat 100g',
            'Flo Coklat 85g', 'Flo Vanila 85g', 'Flo Strawberry 85g',
            'Frisian Flag Kental Manis 370g', 'Frisian Flag Kental Manis 200g',
            'Frisian Flag Purefarm 225ml', 'Frisian Flag Purefarm 400ml',
            'Indomilk Kental Manis 370g', 'Indomilk Kental Manis 200g',
            'Indomilk Coklat 200ml', 'Indomilk Full Cream 200ml',
            'Ultra Milk Full Cream 250ml', 'Ultra Milk Coklat 250ml',
            'Ultra Milk Strawberry 250ml', 'Ultra Milk Full Cream 1L',
            'Greenfields Full Cream 250ml', 'Greenfields Coklat 250ml',
            'Cimory Yogurt Drink 250ml', 'Cimory Squeeze 100g', 'Cimory Yogurt 600ml',
            'Prochiz Cheddar 170g', 'Prochiz Gold 170g', 'Prochiz Mozzarella 200g',
            'Prochiz Slice 200g', 'Prochiz Spready 170g',
            'Meg Keju Cheddar 170g', 'Meg Keju Belcube 125g',
            'Kraft Cheddar 165g', 'Kraft Slice 200g',
            'Dancow Fortigro 800g', 'Dancow Hi-Calcium 800g',
            'Dancow Batita 400g', 'Dancow 1-3 Tahun 400g',
            'Bendera Kental Manis 370g', 'Bendera Full Cream 225ml',
            'Entrasol Active 350g', 'Entrasol Gold 350g',
            'SGM 1 Plus 800g', 'SGM 3 Plus 800g',
            'Morinaga Chil Kid 800g', 'Morinaga Chil School 800g',
            'Bango Kecap Manis 275ml', 'Bango Kecap Manis 520ml',
            'Bango Kecap Manis 135ml', 'Bango Kecap Manis 600ml',
            'Sedaap Kecap Manis 275ml', 'Sedaap Kecap Manis 520ml',
            'Saori Saus Tiram 235ml', 'Saori Saus Sambal 235ml',
            'Royco Kaldu Ayam 100g', 'Royco Kaldu Sapi 100g',
            'Royco Rasa Ayam 480g', 'Royco Rasa Sapi 480g',
            'Masako Kaldu Ayam 100g', 'Masako Kaldu Sapi 100g',
            'Ladaku Merica Bubuk 100g', 'Ladaku Merica Bubuk 50g',
            'Desaku Kunyit Bubuk 100g', 'Desaku Ketumbar Bubuk 100g',
            'Desaku Marinasi 100g', 'Desaku Balado 100g',
            'Koepoe Koepoe Kunyit Bubuk 50g', 'Koepoe Koepoe Ketumbar Bubuk 50g',
            'Sasa Tepung Bakwan 500g', 'Sasa Tepung Ayam Crispy 500g',
            'Ajinomoto 500g', 'Ajinomoto 250g', 'Ajinomoto 1kg',
            'Gula Gulaku Premium 1kg', 'Gula Gulaku 500g',
            'Blue Band Serbaguna 200g', 'Blue Band Master 225g',
            'Filma Margarin 200g', 'Filma Margarin 500g',
            'Tropical Minyak Goreng 2L', 'Tropical Minyak Goreng 1L',
            'Barco Minyak Goreng 2L', 'Barco Minyak Goreng 1L',
            'Rose Brand Tepung Beras 500g', 'Rose Brand Tepung Beras 1kg',
            'Medali Emas Beras 5kg', 'Medali Emas Beras 10kg',
            'Rajawali Tepung Terigu 1kg', 'Rajawali Tepung Terigu 500g',
            'Lion Brothers Kecap Manis 600ml', 'Lion Brothers Kecap Asin 600ml',
            'Mie Sedaap Goreng 85g', 'Mie Sedaap Kuah 75g',
            'Mie Sedaap Goreng Sambal Matah 85g', 'Mie Sedaap Goreng Korean 85g',
            'Pop Mie Ayam 75g', 'Pop Mie Baso 75g',
            'Sarimi Isi 2 Ayam Bawang 110g', 'Sarimi Isi 2 Kari Ayam 110g',
            'Supermi Ayam Bawang 70g', 'Supermi Soto 70g',
            'Energen Coklat 295g', 'Energen Vanila 295g',
            'Energen Kacang Hijau 295g', 'Energen Jagung 295g',
            'Koko Krunch 300g', 'Koko Krunch 600g',
            'Honey Stars 300g', 'Honey Stars 600g',
            'Cerelac Beras Madu 300g', 'Cerelac Beras Kentang 300g',
            'Promina 120g', 'Promina 240g',
            'Kopi ABC 100g', 'Kopi ABC 200g',
            'Kopi ABC Susu 15s', 'Kopi ABC Original 15s',
            'Torabika Cappuccino 15s', 'Torabika Mocacinno 15s',
            'Torabika Original 100g', 'Torabika Special 100g',
            'ABC Sambal Terasi 275ml', 'ABC Sambal Manis 275ml',
            'ABC Kecap Manis 275ml', 'ABC Kecap Manis 600ml',
            'ABC Saus Tomat 275ml', 'ABC Saus Sambal 275ml'
        ])[((i - 1) % 180) + 1] AS name
) sub;
